### 딥-러닝 과정 CNN | 2020.02.27. 

### 세번째 실습. Keras 모델 생성/학습 - Fashion MNIST : CNN
[Keras Dataset](https://keras.io/ko/datasets/#-mnist)

In [1]:
# 1. 데이터 불러오기
from keras.datasets import fashion_mnist

(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

Using TensorFlow backend.


(60000, 28, 28)
(10000, 28, 28)
(60000,)
(10000,)


In [2]:
# 2. 이미지 데이터 확인하기 🖼
import matplotlib.pyplot as plt

print(plt.imshow(X_train[0], cmap = plt.cm.gray))
print(y_train[0])


AxesImage(80,52.8;496x369.6)
9


In [3]:
# 3-1. 이미지 데이터 전처리 : 2차원->3차원 🌟🌟🌟
X_train_re = X_train.reshape((60000,28,28,1))
X_test_re = X_test.reshape((10000,28,28,1))

print(X_train_re)

[[[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 ...


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]

In [4]:
# 3-2. 이미지 데이터 전처리 : Normalzation 
X_train_re = X_train_re / 255
X_test_re = X_test_re / 255

In [5]:
# 4. Label categorical (one-hot encoding) 
from keras.utils import to_categorical

y_train_en = to_categorical(y_train)
y_test_en = to_categorical(y_test)

print(y_train_en)
print(y_train_en.shape)

[[0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(60000, 10)


In [6]:
# 5. 모델 생성 : CNN
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
import keras.backend.tensorflow_backend as K
with K.tf.device('/gpu:0'):
    

    model = Sequential()
    model.add(Conv2D(filters = 16,kernel_size = (3,3) ,padding= 'same',input_shape = (28,28,1), activation = 'relu'))
    model.add(MaxPooling2D(pool_size = (2,2)))
    model.add(Dropout(0.3))
    model.add(Flatten())
    model.add(Dense(8, activation = 'relu'))
    model.add(Dense(10, activation = 'softmax'))

    print(model.summary)

<bound method Network.summary of <keras.engine.sequential.Sequential object at 0x7f2b6edd0cf8>>


In [7]:
# 6. Compile - Optimizer, Loss function 설정
import keras.backend.tensorflow_backend as K
with K.tf.device('/gpu:0'):
    
    

SyntaxError: invalid syntax (<ipython-input-7-f645e55c6851>, line 5)

In [ ]:
# 7. 모델 학습시키기
from keras.callbacks import EarlyStopping
early_stop = EarlyStopping(patience = 2)
history = model.fit(X_train_re, y_train_en, nb_epoch = 15, batch_size=5, callbacks=[early_stop], validation_split=0.2)

In [ ]:
# 8. 모델 평가하기
train_acc = model.evaluate(X_train_re, y_train_en)
test_acc = model.evaluate(X_test_re, y_test_en)

print(train_acc)
print(test_acc)

In [ ]:
# 9. 이미지를 랜덤으로 선택해 훈련된 모델로 예측 🖼
import numpy
for index in numpy.random.choice(len(y_test_en), 3, replace = False):
    predicted = model.predict(X_test_re[index:index + 1])[0]
    label = y_test_en[index]
    result_label = numpy.where(label == numpy.amax(label))
    result_predicted = numpy.where(predicted == numpy.amax(predicted))
    title = "Label value = %s  Predicted value = %s " % (result_label[0], result_predicted[0])
    
    fig = plt.figure(1, figsize = (3,3))
    ax1 = fig.add_axes((0,0,.8,.8))
    ax1.set_title(title)
    images = X_test_re
    plt.imshow(images[index].reshape(28, 28), cmap = 'Greys', interpolation = 'nearest')
    plt.show()

In [ ]:
# 10. 학습 시각화하기
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend(['train', 'val'], loc = 'rigth upper')
plt.show()