### Numpy

#### ndarray class

In [1]:
import numpy as np

In [1]:
lst = [1,2,3,4,5]
ar = np.array(lst)

print(lst)
print(ar)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [2]:
type(lst)

list

In [3]:
type(ar)

numpy.ndarray

In [4]:
lst = [[1,2,3],[4,5,6]]
lst

[[1, 2, 3], [4, 5, 6]]

In [6]:
ar = np.array(lst)
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
ar.shape

(2, 3)

In [8]:
ar.ndim

2

#### 여러 배열 만들어보기

In [10]:
ar1 = np.array([10, 8, 15, 7, 19])
ar2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
ar3 = np.array([[[100,90,80],[70,60,50]],[[15,25,35],[45,55,65]],[[11,22,33],[44,55,66]]])

ar1

array([10,  8, 15,  7, 19])

In [11]:
ar2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [12]:
ar3

array([[[100,  90,  80],
        [ 70,  60,  50]],

       [[ 15,  25,  35],
        [ 45,  55,  65]],

       [[ 11,  22,  33],
        [ 44,  55,  66]]])

In [15]:
type(ar1), type(ar2), type(ar3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
len(ar1), len(ar2), len(ar3)

(5, 3, 3)

In [19]:
np.ndim(ar1), np.ndim(ar2), np.ndim(ar3)

(1, 2, 3)

In [20]:
np.shape(ar1), np.shape(ar2), np.shape(ar3)

((5,), (3, 3), (3, 2, 3))

In [24]:
# shape이 2,5,4인 배열 만들기
ar = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]],
              [[21,22,23,24],[25,26,27,28],[29,30,31,32],[33,34,35,36],[37,38,39,40]]])
ar.shape

(2, 5, 4)

In [25]:
# shape이 3,3,3인 배열 만들기
ar = np.array([[[1,2,3],[4,5,6],[7,8,9]],
              [[10,11,12],[13,14,15],[16,17,18]],
              [[19,20,21],[22,23,24],[25,26,27]]])
ar.shape

(3, 3, 3)

In [26]:
ar

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [36]:
# shape이 5,5,2인 배열 만들기
ar = np.array([[[1,2],[3,4],[5,6],[7,8],[9,10]],
              [[11,12],[13,14],[15,16],[17,18],[19,20]],
              [[21,22],[23,24],[25,26],[27,28],[29,30]],
              [[31,32],[33,34],[35,36],[37,38],[39,40]],
              [[41,42],[43,44],[45,46],[47,48],[49,50]]])

ar.shape

(5, 5, 2)

In [37]:
ar

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]],

       [[31, 32],
        [33, 34],
        [35, 36],
        [37, 38],
        [39, 40]],

       [[41, 42],
        [43, 44],
        [45, 46],
        [47, 48],
        [49, 50]]])

#### zeros, ones

In [44]:
ar0 = np.zeros((3,6))

In [45]:
ar0

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [48]:
ar1 = np.ones(((3,2,3)))

In [49]:
ar1

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### arange, reshape

In [68]:
ar = np.arange(10,25)

In [69]:
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [71]:
ar.reshape(3,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
ar = np.arange(11,61)

In [76]:
ar

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [77]:
ar.reshape(2,5,5)

array([[[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60]]])

In [78]:
ar = np.arange(74,250,5)

In [79]:
ar

array([ 74,  79,  84,  89,  94,  99, 104, 109, 114, 119, 124, 129, 134,
       139, 144, 149, 154, 159, 164, 169, 174, 179, 184, 189, 194, 199,
       204, 209, 214, 219, 224, 229, 234, 239, 244, 249])

In [80]:
ar.reshape(3,3,4)

array([[[ 74,  79,  84,  89],
        [ 94,  99, 104, 109],
        [114, 119, 124, 129]],

       [[134, 139, 144, 149],
        [154, 159, 164, 169],
        [174, 179, 184, 189]],

       [[194, 199, 204, 209],
        [214, 219, 224, 229],
        [234, 239, 244, 249]]])

In [2]:
ar0 = np.arange(12)
ar0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
ar0 = ar0.reshape(3,4)

In [5]:
ar0

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
ar0.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
ar0

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
ar = np.random.randint(0,7,(2,3,4))
ar

array([[[3, 6, 1, 5],
        [0, 4, 1, 3],
        [0, 5, 2, 3]],

       [[1, 0, 3, 1],
        [6, 6, 0, 4],
        [1, 6, 6, 6]]])

In [10]:
ar = np.random.randint(-5,5,7)
ar

array([ 0,  4, -5, -4,  4, -4, -1])

np.linespace

In [11]:
ar = np.linespace(0,15,4)
ar

AttributeError: module 'numpy' has no attribute 'linespace'

#### Transpose 행과 열을 교체

In [81]:
ar = np.arange(1,11).reshape(2,5)

In [82]:
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [83]:
ar.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

#### slicing

In [84]:
ar = np.arange(10)

In [85]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
ar[2]

2

In [87]:
ar[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
ar[2:5]

array([2, 3, 4])

In [89]:
ar[2:6:2]

array([2, 4])

In [91]:
ar[::2]

array([0, 2, 4, 6, 8])

In [99]:
ar = np.arange(12)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [101]:
ar = ar.reshape(3,4)

In [102]:
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
ar[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [12]:
ar = np.arange(0,15)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
ar = ar.reshape(3,5)

In [16]:
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
ar[1:,1:]

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [18]:
ar[:2,:1]

array([[0],
       [5]])

In [19]:
ar[1:2, 3:]

array([[8, 9]])

In [21]:
ar = np.arange(0,24).reshape(3,2,4)
ar

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [22]:
ar[1:,1:,:1]

array([[[12]],

       [[20]]])

In [23]:
ar[1:,0:,:3]

array([[[ 8,  9, 10],
        [12, 13, 14]],

       [[16, 17, 18],
        [20, 21, 22]]])

In [24]:
ar[1:3, 1:4, 1:5]

array([[[13, 14, 15]],

       [[21, 22, 23]]])

### Vectorization operation

list와 다르게 array는 연산이 가능하다.

In [25]:
ar = np.array([1,2,3,4,5])
ar*2

array([ 2,  4,  6,  8, 10])

In [26]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c=a+b

In [27]:
c

array([5, 7, 9])

In [28]:
c*2

array([10, 14, 18])

In [29]:
c>10

array([False, False, False])

In [31]:
x = c>8
x

array([False, False,  True])

x는 f,f,t라는 array다

In [32]:
a[x]

array([3])

따라서 a에서 마지막 숫자인 3만 결과값으로 출력된다.

In [33]:
a = np.random.randint(-10, 10, 5)
b = np.random.randint(-10, 10, 5)

In [34]:
a

array([-7,  1,  6,  4, -1])

In [35]:
b

array([ 6, -1, -5,  7,  1])

In [37]:
a*b

array([-42,  -1, -30,  28,  -1])

In [38]:
a+b

array([-1,  0,  1, 11,  0])

In [40]:
a+b*2

array([ 5, -1, -4, 18,  1])

In [41]:
a**2

array([49,  1, 36, 16,  1], dtype=int32)

In [42]:
a>5

array([False, False,  True, False, False])

In [43]:
a%2==1

array([ True,  True, False, False,  True])

In [44]:
np.where(a%2==1)

(array([0, 1, 4], dtype=int64),)

-------------------------------------------------------

In [45]:
ar = np.random.randint(0,10,5)
ar

array([5, 1, 4, 7, 8])

In [46]:
np.exp(ar)

array([1.48413159e+02, 2.71828183e+00, 5.45981500e+01, 1.09663316e+03,
       2.98095799e+03])

In [47]:
np.log(ar[1:])

array([0.        , 1.38629436, 1.94591015, 2.07944154])

In [48]:
np.log(ar)

array([1.60943791, 0.        , 1.38629436, 1.94591015, 2.07944154])

In [49]:
np.log10(ar[1:])

array([0.        , 0.60205999, 0.84509804, 0.90308999])

In [50]:
np.sin(ar)

array([-0.95892427,  0.84147098, -0.7568025 ,  0.6569866 ,  0.98935825])

In [51]:
np.cos(ar)

array([ 0.28366219,  0.54030231, -0.65364362,  0.75390225, -0.14550003])

In [52]:
np.abs(ar)

array([5, 1, 4, 7, 8])

broadcasting

In [53]:
ar0 = np.arange(12).reshape(4,3)
ar1 = np.arange(3)
ar2 = np.arange(4).reshape(4,1)
print(ar0, '\n', ar1, '\n', ar2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 
 [0 1 2] 
 [[0]
 [1]
 [2]
 [3]]


In [54]:
ar0 + ar1

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [55]:
ar0

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
ar1

array([0, 1, 2])

In [57]:
ar0 + ar2

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [58]:
ar1 + ar2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [59]:
ab = np.arange(9).reshape(3,3)
ab

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
ar0 + ab # 행이나 열 모두 맞지 않는 행렬은 broadcasting이 되지 않는다.

ValueError: operands could not be broadcast together with shapes (4,3) (3,3) 

In [64]:
ar0 = np.array([7,5,9,10])
ar1 = np.array([4,10,6,2])
ar0

array([ 7,  5,  9, 10])

In [65]:
ar1

array([ 4, 10,  6,  2])

In [66]:
ar0*3 + ar1*3

array([33, 45, 45, 36])

In [69]:
ar = np.array(list(ar0)+list(ar1))
ar = ar.reshape(2,4)

In [70]:
ar

array([[ 7,  5,  9, 10],
       [ 4, 10,  6,  2]])

In [71]:
ar1 = np.array([1,3,4,9,14,7,6,4]).reshape(2,4)
ar1

array([[ 1,  3,  4,  9],
       [14,  7,  6,  4]])

In [72]:
ar_ = ar - ar1

In [73]:
ar_

array([[  6,   2,   5,   1],
       [-10,   3,   0,  -2]])

In [74]:
ar_>0

array([[ True,  True,  True,  True],
       [False,  True, False, False]])

In [75]:
a = np.array([3,6,8,10,11])
b = np.ndarray(50).reshape(2,5,5)

In [77]:
A = np.arange(1,13).reshape(3,4)
B = np.random.randint(1,13,3).reshape(3,1)

In [79]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [80]:
B

array([[5],
       [7],
       [5]])

In [81]:
C = A+B
C_ = B+A

In [82]:
C==C_

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [83]:
C

array([[ 6,  7,  8,  9],
       [12, 13, 14, 15],
       [14, 15, 16, 17]])

In [84]:
C_

array([[ 6,  7,  8,  9],
       [12, 13, 14, 15],
       [14, 15, 16, 17]])

#### 다양한 기능  
min, max

In [85]:
ar = np.random.random((2,4,4))
ar

array([[[0.36935147, 0.65441428, 0.0540003 , 0.59008167],
        [0.52966205, 0.60292606, 0.09504033, 0.91593285],
        [0.65258487, 0.56514046, 0.75657752, 0.31762502],
        [0.84550781, 0.93020343, 0.94500274, 0.71425434]],

       [[0.41986569, 0.71853723, 0.38463315, 0.11606014],
        [0.51562091, 0.7816781 , 0.04707638, 0.6746623 ],
        [0.82972376, 0.70029306, 0.22590392, 0.20305369],
        [0.91776048, 0.0966254 , 0.11923434, 0.79469575]]])

In [86]:
np.max(ar)

0.9450027409128523

In [87]:
np.where(np.max(ar))

(array([0], dtype=int64),)

In [88]:
np.min(ar)

0.04707637856896807

In [89]:
np.where(ar>0.5)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       dtype=int64),
 array([0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 0, 1, 1, 1, 2, 2, 3, 3],
       dtype=int64),
 array([1, 3, 0, 1, 3, 0, 1, 2, 0, 1, 2, 3, 1, 0, 1, 3, 0, 1, 0, 3],
       dtype=int64))

In [90]:
ar = np.random.randint(1,100,(3,4,4))

In [91]:
ar

array([[[25, 31, 33, 39],
        [22, 98, 70, 57],
        [79, 67, 43,  9],
        [98,  4, 95,  7]],

       [[17, 82, 62,  9],
        [31, 44,  7, 18],
        [80, 93, 20, 37],
        [26, 54, 17, 26]],

       [[40, 72, 95, 32],
        [14, 21, 62, 90],
        [43,  7, 32, 75],
        [88, 46, 27, 24]]])

In [92]:
np.max(ar)

98

In [93]:
np.where(np.max(ar))

(array([0], dtype=int64),)

argmin, argmax

In [97]:
ar = np.random.random(10)
ar

array([0.1640473 , 0.58421835, 0.47373069, 0.67337966, 0.06463462,
       0.50095769, 0.61152138, 0.15626496, 0.88390736, 0.13293984])

In [98]:
ar = ar.reshape(2,5)

In [99]:
ar

array([[0.1640473 , 0.58421835, 0.47373069, 0.67337966, 0.06463462],
       [0.50095769, 0.61152138, 0.15626496, 0.88390736, 0.13293984]])

In [100]:
np.argmin(ar)

4

최소값의 인덱스가 나타난다.

In [101]:
np.argmax(ar)

8

최대값의 인덱스가 나타난다.

In [106]:
np.argmin(ar[:1,]) # slicing을 사용하여 범위를 지정한 상태에서 사용할 수 있다.

4

#### sum, mean, median

In [107]:
ar = np.arange(1, 31, 2).reshape(3,5)
ar

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [108]:
np.sum(ar) # 배열의 합

225

In [110]:
np.mean(ar) # 배열의 평균

15.0

In [111]:
np.median(ar) # 배열의 중앙값

15.0

In [120]:
ar = np.random.randint(1,5000,(5,4,8))

In [121]:
ar

array([[[3137, 4147, 1365,  183, 2313,  401, 1782, 4110],
        [2043, 4663, 1729, 4162, 2501, 3188, 1562,  323],
        [2293,  720,  382, 4633,  594, 2471, 2236,  274],
        [1928, 1178, 2368, 4930,   36, 3703,   86, 1851]],

       [[2110,  958,  739, 4449, 3016, 4523, 1360, 4495],
        [2198,  566,  930,  725, 4721, 3375, 3656, 3755],
        [ 134,  819, 3349, 2994, 4926, 4854, 4549, 1383],
        [ 590, 2567,  866, 4209, 2574, 4538, 3470, 2855]],

       [[3648, 2315, 2567, 2248, 3699, 2021, 3706,  296],
        [1537, 1015, 4093, 4151, 3476, 3349, 4206,  958],
        [4360, 2251, 3704, 3396,  413, 4531, 1851, 1158],
        [3190,  282, 1920, 3719, 3012, 4022, 4674, 1785]],

       [[2856, 4347, 1016, 1215, 1928, 3774, 3607,   34],
        [2537,  932,  689, 3063, 3430, 3346, 2409, 2071],
        [2012,  605, 4566,  110, 4684, 2782, 4966, 2654],
        [1496, 1576, 4907, 4621, 3140, 3782,  245, 1233]],

       [[3917,  661, 4779, 1309, 2330, 1831, 4959, 2134],
      

In [122]:
np.sum(ar)

415959

In [123]:
np.mean(ar)

2599.74375

In [124]:
np.median(ar)

2566.5

In [125]:
np.sum(ar, axis=0)

array([[15668, 12428, 10466,  9404, 13286, 12550, 15414, 11069],
       [11405, 10205, 10799, 16749, 15935, 17033, 16102,  9249],
       [ 9809,  6244, 12987, 14955, 13183, 19265, 16945,  6677],
       [12165,  9927, 14290, 21565,  9067, 17523, 13098, 10497]])

In [126]:
np.sum(ar, axis=1)

array([[ 9401, 10708,  5844, 13908,  5444,  9763,  5666,  6558],
       [ 5032,  4910,  5884, 12377, 15237, 17290, 13035, 12488],
       [12735,  5863, 12284, 13514, 10600, 13923, 14437,  4197],
       [ 8901,  7460, 11178,  9009, 13182, 13684, 11227,  5992],
       [12978,  9863, 13352, 13865,  7008, 11711, 17194,  8257]])

In [127]:
np.sum(ar[1:], axis=0)

array([[12531,  8281,  9101,  9221, 10973, 12149, 13632,  6959],
       [ 9362,  5542,  9070, 12587, 13434, 13845, 14540,  8926],
       [ 7516,  5524, 12605, 10322, 12589, 16794, 14709,  6403],
       [10237,  8749, 11922, 16635,  9031, 13820, 13012,  8646]])

In [128]:
a = np.array([[[0.5,2,4,-5],[0.7,9,3,0.7],[8,1,-2,0.3]]])
a

array([[[ 0.5,  2. ,  4. , -5. ],
        [ 0.7,  9. ,  3. ,  0.7],
        [ 8. ,  1. , -2. ,  0.3]]])

In [129]:
np.sum(a), np.mean(a), np.median(a)

(22.2, 1.8499999999999999, 0.85)

In [130]:
b = np.array([[1.2,4,2,-9],[8,3,2,1],[2,8,5,-1]])
b

array([[ 1.2,  4. ,  2. , -9. ],
       [ 8. ,  3. ,  2. ,  1. ],
       [ 2. ,  8. ,  5. , -1. ]])

In [135]:
np.sum(b[1:2,]), np.min(b[1:2,]), np.max(b[1:2,])

(14.0, 1.0, 8.0)

In [136]:
c = np.array([[3,9,6,0.8],[0.9,-1,3,4],[2,5,7,9]])
c

array([[ 3. ,  9. ,  6. ,  0.8],
       [ 0.9, -1. ,  3. ,  4. ],
       [ 2. ,  5. ,  7. ,  9. ]])

In [139]:
np.max(c[:,1:2]), np.min(c[:,1:2]), np.mean(c[:,1:2]), np.median(c[:,1:2])

(9.0, -1.0, 4.333333333333333, 5.0)

#### 행렬곱

행렬곱은 스칼라곱과 구별된다  
a*b 와 a@b가 다르다.

In [140]:
a = np.arange(1,21,2).reshape(2,5)
b = np.arange(3,13,1).reshape(5,2)

In [141]:
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [142]:
b

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [144]:
a@b

array([[215, 240],
       [565, 640]])

In [147]:
a.T*b

array([[  3,  44],
       [ 15,  78],
       [ 35, 120],
       [ 63, 170],
       [ 99, 228]])

In [149]:
a = np.array([3,2,-1,0,2,4]).reshape(2,3)
b = np.array([2,2,3,4,5,1]).reshape(3,2)
a@b

array([[ 7, 13],
       [26, 12]])

In [150]:
c = np.array([1,9,3,4,2,4]).reshape(3,2)
d = np.array([1,4,-1,7,1,4]).reshape(2,3)
c@d

array([[64, 13, 35],
       [31, 16, 13],
       [30, 12, 14]])

In [171]:
(a@b) == (b@a)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [152]:
a@b

array([[ 7, 13],
       [26, 12]])

In [153]:
b@a

array([[ 6,  8,  6],
       [ 9, 14, 13],
       [15, 12, -1]])

In [156]:
a@(b+c)

array([[14, 44],
       [40, 36]])

In [157]:
a@b + a@c

array([[14, 44],
       [40, 36]])

In [163]:
(a.T+b)@d

array([[19, 22,  3],
       [47, 26, 19],
       [39, 21, 16]])

In [164]:
a.T@d + b@d

array([[19, 22,  3],
       [47, 26, 19],
       [39, 21, 16]])

In [165]:
a@b

array([[ 7, 13],
       [26, 12]])

In [166]:
(a@b).T

array([[ 7, 26],
       [13, 12]])

In [167]:
a.T@b.T

array([[ 6,  9, 15],
       [ 8, 14, 12],
       [ 6, 13, -1]])

In [168]:
b.T@a.T

array([[ 7, 26],
       [13, 12]])

In [169]:
(b.T@a.T)

array([[ 7, 26],
       [13, 12]])

In [170]:
(b@a).T

array([[ 6,  9, 15],
       [ 8, 14, 12],
       [ 6, 13, -1]])

#### 표준편차 분산

In [172]:
np.var(a)

2.8888888888888893

In [173]:
np.std(a)

1.699673171197595

In [174]:
a

array([[ 3,  2, -1],
       [ 0,  2,  4]])

np.random.shuffle 배열 섞기

In [184]:
ar = np.random.shuffle(a)

In [186]:
a

array([[ 0,  2,  4],
       [ 3,  2, -1]])

In [187]:
ar = np.arange(1,16)

In [188]:
np.random.shuffle(ar)

In [189]:
ar = ar.reshape(3,5)

In [190]:
ar

array([[ 8, 15, 11,  4,  6],
       [ 7,  1,  2, 12,  3],
       [10,  5, 13,  9, 14]])

np.sort 배열 정렬하기

In [191]:
ar2 = np.sort(ar)

In [192]:
ar2

array([[ 4,  6,  8, 11, 15],
       [ 1,  2,  3,  7, 12],
       [ 5,  9, 10, 13, 14]])

In [193]:
ar3 = np.sort(ar, axis=0)

In [194]:
ar3

array([[ 7,  1,  2,  4,  3],
       [ 8,  5, 11,  9,  6],
       [10, 15, 13, 12, 14]])

In [195]:
ar = np.random.randint(-10,10,(2,5))
ar

array([[  2,  -6,   6,   7,   3],
       [  9, -10,   5,   6,  -7]])

In [196]:
np.unique(ar)

array([-10,  -7,  -6,   2,   3,   5,   6,   7,   9])

In [197]:
a = np.random.randint(1,101, (10,10))
a

array([[ 38,  63,  46,  97,  67,  40,  48,  44,  88,  11],
       [ 31,  46,  60,   1, 100,  60,  81,   7,  53,  37],
       [ 72,   5,  85,  62,  12, 100,  62,  59,  61,  77],
       [ 90,  91,  66,  62,  77,  79,  23,  73,  68,  44],
       [ 68,  51,  51,  14,  34,  96,  87,  17,  92,  45],
       [ 13,  93,  36,  43,  75,  76,  83,  76,  35,   3],
       [ 19,  42,  63,  87,  22,  25,  79,  55,  62,  40],
       [ 92,  42,  25,  35,  22,  73,   4,  68,  73,  72],
       [100,  69,  87,  13,  38,  20,  28,  76,   5,  81],
       [ 36,  48,  44,  98,   1,  91,  20,  34,   9,  17]])

In [198]:
np.random.shuffle(a)

In [199]:
a

array([[ 31,  46,  60,   1, 100,  60,  81,   7,  53,  37],
       [ 90,  91,  66,  62,  77,  79,  23,  73,  68,  44],
       [ 19,  42,  63,  87,  22,  25,  79,  55,  62,  40],
       [100,  69,  87,  13,  38,  20,  28,  76,   5,  81],
       [ 13,  93,  36,  43,  75,  76,  83,  76,  35,   3],
       [ 68,  51,  51,  14,  34,  96,  87,  17,  92,  45],
       [ 92,  42,  25,  35,  22,  73,   4,  68,  73,  72],
       [ 38,  63,  46,  97,  67,  40,  48,  44,  88,  11],
       [ 72,   5,  85,  62,  12, 100,  62,  59,  61,  77],
       [ 36,  48,  44,  98,   1,  91,  20,  34,   9,  17]])

In [209]:
b = np.random.randint(1,31, (3,10))
b

array([[17, 17,  6, 25, 17, 12, 12,  9,  2, 13],
       [14, 29,  7,  1, 24, 17,  3,  6,  9, 19],
       [ 5, 28, 24,  3, 19, 26, 12, 14, 29, 26]])

In [210]:
np.random.shuffle(b)

In [211]:
b

array([[14, 29,  7,  1, 24, 17,  3,  6,  9, 19],
       [ 5, 28, 24,  3, 19, 26, 12, 14, 29, 26],
       [17, 17,  6, 25, 17, 12, 12,  9,  2, 13]])

In [212]:
b = np.sort(b, axis=0)

In [213]:
b

array([[ 5, 17,  6,  1, 17, 12,  3,  6,  2, 13],
       [14, 28,  7,  3, 19, 17, 12,  9,  9, 19],
       [17, 29, 24, 25, 24, 26, 12, 14, 29, 26]])

In [214]:
c = np.arange(1,101)

In [215]:
c

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [216]:
np.random.shuffle(c)

In [217]:
c

array([ 86,  19,  87,  76,  64,  16,  63,  18,   1,   8, 100,  99,  42,
        66,  69,  45,  43,  93,  75,  26,  92,  49,  73,  62,  29,  77,
        88,   7,  74,  11,  94,  48,  90,  61,  70,  82,  44,  24,  36,
        58,  85,  25,  53,  30,  56,  65,  27,  17,  47,  68,  59,  71,
        12,  67,  84,  32,  83,  23,  35,   6,  39,   5,  41,  81,  38,
        10,   9,  37,  15,  89,  52,  51,  50,  72,  46,  13,  97,  31,
         2,  96,  28,  54,  91,  20,  21,  78,  55,  40,  57,  34,  22,
         4,  14,  79,  98,  80,  60,  33,  95,   3])

In [218]:
c.reshape(10,10)

array([[ 86,  19,  87,  76,  64,  16,  63,  18,   1,   8],
       [100,  99,  42,  66,  69,  45,  43,  93,  75,  26],
       [ 92,  49,  73,  62,  29,  77,  88,   7,  74,  11],
       [ 94,  48,  90,  61,  70,  82,  44,  24,  36,  58],
       [ 85,  25,  53,  30,  56,  65,  27,  17,  47,  68],
       [ 59,  71,  12,  67,  84,  32,  83,  23,  35,   6],
       [ 39,   5,  41,  81,  38,  10,   9,  37,  15,  89],
       [ 52,  51,  50,  72,  46,  13,  97,  31,   2,  96],
       [ 28,  54,  91,  20,  21,  78,  55,  40,  57,  34],
       [ 22,   4,  14,  79,  98,  80,  60,  33,  95,   3]])

In [219]:
np.argmin(c), np.argmax(c)

(8, 10)

In [220]:
np.sum(c), np.median(c)

(5050, 50.5)

#### Deep copy, shallow copy

Deep copy = 새롭게 생성  
shallow copy = 같은 곳을 참조

In [222]:
a = np.arange(1,10).reshape(3,3)

In [223]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [247]:
dar = a # deep copy

In [227]:
dar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [228]:
dar[0][2]

3

In [229]:
b = np.arange(1,10).reshape(3,3)

In [230]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [246]:
dbr = b.copy() # deep copy

In [233]:
dbr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [234]:
dbr[0][2]

3

In [235]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [236]:
dar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [237]:
np.random.shuffle(a)

In [238]:
a

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [239]:
dar

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

a의 배열이 바뀌면 a의 복사본도 함께 바뀐다.-> shallow copy

In [240]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [241]:
dbr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [242]:
np.random.shuffle(b)

In [243]:
b

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [244]:
dbr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

b의 배열이 바뀌었지만 b의 복사본은 유지되었다. deep copy

In [248]:
a

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

### 배열 텍스트 파일로 저장하기

In [249]:
np.savetxt('File0.txt', a)

In [250]:
ar = np.loadtxt('File0.txt')
ar

array([[7., 8., 9.],
       [4., 5., 6.],
       [1., 2., 3.]])

In [256]:
np.savetxt('File1.csv', a)

저장한 파일 불러오기

In [253]:
ar0 = np.loadtxt('File1.csv')

In [254]:
ar0

array([[7., 8., 9.],
       [4., 5., 6.],
       [1., 2., 3.]])

In [257]:
ar

array([[7., 8., 9.],
       [4., 5., 6.],
       [1., 2., 3.]])

In [259]:
b = np.arange(200).reshape(2,10,10)

In [260]:
b

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [262]:
np.savetxt('File2.txt', b) # 3차원 부터는 저장 X

ValueError: Expected 1D or 2D array, got 3D array instead

In [263]:
price = np.loadtxt('price.txt')

In [264]:
qnt = np.loadtxt('qnt.txt')

In [265]:
price

array([[3000., 2300., 2500., 1900., 1800., 1500., 1600.],
       [2500., 6300., 1500., 1800., 1700., 1400., 5600.],
       [9800., 9600., 5200., 6500., 4500., 2000., 2300.]])

In [266]:
qnt

array([[5., 4., 8., 5., 5., 6., 1.],
       [5., 2., 2., 6., 3., 6., 9.],
       [7., 8., 8., 9., 5., 6., 9.]])

In [267]:
sales = price*qnt

In [268]:
sales

array([[15000.,  9200., 20000.,  9500.,  9000.,  9000.,  1600.],
       [12500., 12600.,  3000., 10800.,  5100.,  8400., 50400.],
       [68600., 76800., 41600., 58500., 22500., 12000., 20700.]])

In [272]:
np.savetxt('sales.txt', sales)

### 학생 성적 파일 불러와서 계산하기

In [304]:
score = np.loadtxt('score.txt')

In [305]:
score

array([[  1.,  70.,  85.,  95., 100., 100.],
       [  2., 100.,  85.,  90.,  90.,  95.],
       [  3.,  95.,  95.,  80.,  75.,  75.],
       [  4.,  65.,  75.,  70.,  90., 100.],
       [  5.,  90.,  80.,  85.,  95.,  95.],
       [  6.,  90.,  90.,  75.,  75.,  80.],
       [  7.,  60.,  90.,  80.,  40.,  45.],
       [  8.,  85.,  90.,  75.,  60.,  90.],
       [  9.,  90.,  85.,  85.,  90.,  85.]])

컬럼은 앞에서부터 학번, 영어, 국어, 수학, 체육, 컴퓨터이다

학생들의 평균 점수를 구해보자

In [306]:
np.mean(score[:1, 1:]), np.mean(score[1:2, 1:])

(90.0, 92.0)

In [307]:
for i in range(1,10):
    print(i,'번 학생 평균 점수: ',np.mean(score[i-1:i, 1:]))

1 번 학생 평균 점수:  90.0
2 번 학생 평균 점수:  92.0
3 번 학생 평균 점수:  84.0
4 번 학생 평균 점수:  80.0
5 번 학생 평균 점수:  89.0
6 번 학생 평균 점수:  82.0
7 번 학생 평균 점수:  63.0
8 번 학생 평균 점수:  80.0
9 번 학생 평균 점수:  87.0


평균 점수가 가장 높은 학생은 2번 학생이고,  
평균 점수가 가장 낮은 학생은 7번 학생이다.

In [308]:
for i in range(1,10):
    print(i,'번 학생 국어,영어,수학 평균 점수: ',np.mean(score[i-1:i, 1:4]))

1 번 학생 국어,영어,수학 평균 점수:  83.33333333333333
2 번 학생 국어,영어,수학 평균 점수:  91.66666666666667
3 번 학생 국어,영어,수학 평균 점수:  90.0
4 번 학생 국어,영어,수학 평균 점수:  70.0
5 번 학생 국어,영어,수학 평균 점수:  85.0
6 번 학생 국어,영어,수학 평균 점수:  85.0
7 번 학생 국어,영어,수학 평균 점수:  76.66666666666667
8 번 학생 국어,영어,수학 평균 점수:  83.33333333333333
9 번 학생 국어,영어,수학 평균 점수:  86.66666666666667


국어, 영어, 수학 점수의 평균이 가장 높은 학생은 2번 학생이다.

국어,영어,수학 점수에 2배의 가중치를 준다면 어느 학생의 학업 성취도가 가장 높을까?

In [284]:
w = np.array([1,2,2,2,1,1]) # 가중치 배열 만들기

In [309]:
score

array([[  1.,  70.,  85.,  95., 100., 100.],
       [  2., 100.,  85.,  90.,  90.,  95.],
       [  3.,  95.,  95.,  80.,  75.,  75.],
       [  4.,  65.,  75.,  70.,  90., 100.],
       [  5.,  90.,  80.,  85.,  95.,  95.],
       [  6.,  90.,  90.,  75.,  75.,  80.],
       [  7.,  60.,  90.,  80.,  40.,  45.],
       [  8.,  85.,  90.,  75.,  60.,  90.],
       [  9.,  90.,  85.,  85.,  90.,  85.]])

In [286]:
w

array([1, 2, 2, 2, 1, 1])

In [310]:
score_w = score*w

In [311]:
score_w

array([[  1., 140., 170., 190., 100., 100.],
       [  2., 200., 170., 180.,  90.,  95.],
       [  3., 190., 190., 160.,  75.,  75.],
       [  4., 130., 150., 140.,  90., 100.],
       [  5., 180., 160., 170.,  95.,  95.],
       [  6., 180., 180., 150.,  75.,  80.],
       [  7., 120., 180., 160.,  40.,  45.],
       [  8., 170., 180., 150.,  60.,  90.],
       [  9., 180., 170., 170.,  90.,  85.]])

학생들의 국어, 영어, 수학 점수에 2배의 가중치를 부여하였다. (다른 과목은 유지)

In [312]:
score_ws = np.sum(score_w[:1,1:])
score_ws

700.0

In [313]:
score_ws = []
for i in range(1,10):
    score_wsi = np.sum(score_w[i-1:i,1:])
    score_ws.append(score_wsi) # 학생들의 가중치 합을 리스트에 담는다.
    print(score_ws)

[700.0]
[700.0, 735.0]
[700.0, 735.0, 690.0]
[700.0, 735.0, 690.0, 610.0]
[700.0, 735.0, 690.0, 610.0, 700.0]
[700.0, 735.0, 690.0, 610.0, 700.0, 665.0]
[700.0, 735.0, 690.0, 610.0, 700.0, 665.0, 545.0]
[700.0, 735.0, 690.0, 610.0, 700.0, 665.0, 545.0, 650.0]
[700.0, 735.0, 690.0, 610.0, 700.0, 665.0, 545.0, 650.0, 695.0]


In [314]:
score_ws # 학생들의 가중치 점수 합

[700.0, 735.0, 690.0, 610.0, 700.0, 665.0, 545.0, 650.0, 695.0]

In [315]:
score_wsa = np.array(score_ws)
score_wsa # 가중치 합 리스트를 배열로 전환한다.

array([700., 735., 690., 610., 700., 665., 545., 650., 695.])

In [316]:
score_wsa = score_wsa/8

In [317]:
score_wsa #가중치 평균을 구한다.

array([87.5  , 91.875, 86.25 , 76.25 , 87.5  , 83.125, 68.125, 81.25 ,
       86.875])

In [318]:
score_wsa.reshape(9,1)

array([[87.5  ],
       [91.875],
       [86.25 ],
       [76.25 ],
       [87.5  ],
       [83.125],
       [68.125],
       [81.25 ],
       [86.875]])

가중치를 적용한 점수의 평균이 가장 높은 학생은 2번 학생이다.