In [1]:
import numpy as np

In [8]:
score = np.array([[50,60,80],[80,70,90],[70,80,80]])
score

array([[50, 60, 80],
       [80, 70, 90],
       [70, 80, 80]])

In [13]:
score_sum = np.array([np.sum(score[0,]), np.sum(score[1,]), np.sum(score[2,])])
score_sum

array([190, 240, 230])

In [15]:
major_avg = np.array([np.average(score[:,0]), np.average(score[:,1]), np.average(score[:,2])])
major_avg

array([66.66666667, 70.        , 83.33333333])

# Pandas

### Series

In [2]:
import pandas as pd

In [24]:
score = [84,65,52,55,10,23]
s = pd.Series(score)
print(s)

0    84
1    65
2    52
3    55
4    10
5    23
dtype: int64


In [29]:
names = ['경원', '현우', '충현', '경동', '철수', '영희']
s = pd.Series(score, index= names)

print(s)

경원    84
현우    65
충현    52
경동    55
철수    10
영희    23
dtype: int64


In [30]:
dic = {'경원':84, '현우':55, '충현':44, '경동':66, '철수':77, '영희':22}
s = pd.Series(dic)
print(s)

경원    84
현우    55
충현    44
경동    66
철수    77
영희    22
dtype: int64


In [51]:
dic2 ={'철수':44, '경동':55, '충현':77, '현우':63, '영희':41, '경원':66}
s2 = pd.Series(dic2)

ss = s + s2
print(s)
print(s2)
print(ss)

경원    84
현우    55
충현    44
경동    66
철수    77
영희    22
dtype: int64
철수    44
경동    55
충현    77
현우    63
영희    41
경원    66
dtype: int64
경동    121
경원    150
영희     63
철수    121
충현    121
현우    118
dtype: int64


In [45]:
s[1:2]

현우    55
dtype: int64

In [46]:
s[1:3]

현우    55
충현    44
dtype: int64

In [48]:
s['경동':'영희']

경동    66
철수    77
영희    22
dtype: int64

In [52]:
ss['현우']

118

In [53]:
ss[2:6:2]

영희     63
충현    121
dtype: int64

In [56]:
s[0:2]

경원    84
현우    55
dtype: int64

In [57]:
ss['현우'] = 66
print(ss)

경동    121
경원    150
영희     63
철수    121
충현    121
현우     66
dtype: int64


In [59]:
ss['짱구'] = 588
ss

경동    121
경원    150
영희     63
철수    121
충현    121
현우     66
짱구    588
dtype: int64

In [60]:
del ss['철수']
ss

경동    121
경원    150
영희     63
충현    121
현우     66
짱구    588
dtype: int64

In [61]:
x = s >70
x

경원     True
현우    False
충현    False
경동    False
철수     True
영희    False
dtype: bool

In [63]:
s2[x]

철수    44
경원    66
dtype: int64

In [79]:
names = input('학생들의 이름 입력(,로 구분): ').split(',')
kor = input('국어성적 입력: ').split(',')
eng = input('영어성적 입력: ').split(',')
math = input('수학성적 입력: ').split(',')


kor = [int (i) for i in kor]
eng = [int (i) for i in eng]
math = [int (i) for i in math]

kr = pd.Series(kor, index=names)
eg = pd.Series(eng, index=names)
mt = pd.Series(math, index=names)
sm = kr+eg+mt
avg = sm/3

print('국어 성적')
print(kr)
print('영어 성적')
print(eg)
print('수학 성적')
print(mt)
print('합계')
print(sm)
print('평균')
print(avg)

학생들의 이름 입력(,로 구분): a,b,c
국어성적 입력: 1,1,1
영어성적 입력: 2,2,2
수학성적 입력: 1,2,3
국어 성적
a    1
b    1
c    1
dtype: int64
영어 성적
a    2
b    2
c    2
dtype: int64
수학 성적
a    1
b    2
c    3
dtype: int64
합계
a    4
b    5
c    6
dtype: int64
평균
a    1.333333
b    1.666667
c    2.000000
dtype: float64


In [76]:
kor

array(['10', '10', '10'], dtype='<U2')

### DataFrame

In [81]:
dic1 = {'a':10, 'b':15, 'c':20, 'd':25, 'e':30}
dic2 = {'a':9, 'b':54, 'c':12, 'd':7, 'e':66}

s1 = pd.Series(dic1)
s2 = pd.Series(dic2)

d = pd.DataFrame()
d['kor'] = s1
d['eng'] = s2
d['sum'] = s1 + s2
d

kor  eng  sum
a   10    9   19
b   15   54   69
c   20   12   32
d   25    7   32
e   30   66   96

In [82]:
score = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
names = ['a', 'b', 'c', 'd']
lectures = ['kor', 'eng', 'math']

d2 = pd.DataFrame(score, index=names, columns=lectures)
d2

kor  eng  math
a    1    2     3
b    4    5     6
c    7    8     9
d   10   11    12

In [84]:
d2_ = pd.DataFrame(score)
d2_

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [85]:
d2__ = pd.DataFrame(score, index=names)
d2__

0   1   2
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

In [86]:
d.shape

(5, 3)

In [87]:
d.columns

Index(['kor', 'eng', 'sum'], dtype='object')

In [88]:
d.dtypes

kor    int64
eng    int64
sum    int64
dtype: object

In [89]:
d.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, a to e
Data columns (total 3 columns):
kor    5 non-null int64
eng    5 non-null int64
sum    5 non-null int64
dtypes: int64(3)
memory usage: 160.0+ bytes


In [90]:
scorewithlecture = {'a':[1,2,3,4,5,6], 'b':[7,8,9,4,5,6], 'c':[4,5,6,1,2,3]}
names = ['aa', 'bb', 'cc', 'dd', 'ee', 'ff']

d3 =  pd.DataFrame(scorewithlecture, index=names)
d3

a  b  c
aa  1  7  4
bb  2  8  5
cc  3  9  6
dd  4  4  1
ee  5  5  2
ff  6  6  3

#### index 수정하기

In [91]:
d3

a  b  c
aa  1  7  4
bb  2  8  5
cc  3  9  6
dd  4  4  1
ee  5  5  2
ff  6  6  3

In [92]:
d3.index = ['a','b','c','d','e','f']
d3

a  b  c
a  1  7  4
b  2  8  5
c  3  9  6
d  4  4  1
e  5  5  2
f  6  6  3

In [94]:
d3.rename(index={'e':'el', 'b':'be'})
d3

a  b  c
a  1  7  4
b  2  8  5
c  3  9  6
d  4  4  1
e  5  5  2
f  6  6  3

In [95]:
d3.rename(index={'e':'el', 'b':'be'}, inplace=True)
d3

a  b  c
a   1  7  4
be  2  8  5
c   3  9  6
d   4  4  1
el  5  5  2
f   6  6  3

In [96]:
d3.columns = ['kor', 'eng', 'math']
d3

kor  eng  math
a     1    7     4
be    2    8     5
c     3    9     6
d     4    4     1
el    5    5     2
f     6    6     3

In [109]:
d3.rename(columns={'kor2':'artec'}, inplace=True) # inplace = True -> 원본을 바꿔주기
d3

kor  artec  math
a     1      7     4
be    2      8     5
c     3      9     6
d     4      4     1
el    5      5     2
f     6      6     3

In [110]:
d3[sorted(d3.columns)]
d3

kor  artec  math
a     1      7     4
be    2      8     5
c     3      9     6
d     4      4     1
el    5      5     2
f     6      6     3

In [113]:
cc = ['artec', 'math', 'kor']
d3[cc]

artec  math  kor
a       7     4    1
be      8     5    2
c       9     6    3
d       4     1    4
el      5     2    5
f       6     3    6

In [114]:
d3

kor  artec  math
a     1      7     4
be    2      8     5
c     3      9     6
d     4      4     1
el    5      5     2
f     6      6     3

#### drop index 삭제

In [115]:
d3.drop('el', axis=0)
d3

kor  artec  math
a     1      7     4
be    2      8     5
c     3      9     6
d     4      4     1
el    5      5     2
f     6      6     3

In [118]:
d3.drop('be', axis=0)

kor  artec  math
a     1      7     4
c     3      9     6
d     4      4     1
el    5      5     2
f     6      6     3

#### drop 열 삭제 axis =1

In [119]:
d3.drop('artec', axis=1)

kor  math
a     1     4
be    2     5
c     3     6
d     4     1
el    5     2
f     6     3

In [121]:
d3.loc['be']

kor      2
artec    8
math     5
Name: be, dtype: int64

행 추가하기

In [127]:
d3.loc['sum'] = d3.sum(axis = 0)
d3

kor  artec  math
a     1.0    7.0   4.0
be    2.0    8.0   5.0
c     3.0    9.0   6.0
d     4.0    4.0   1.0
el    5.0    5.0   2.0
f     6.0    6.0   3.0
sum  42.0   78.0  42.0

In [128]:
d3.drop('sum', axis=0)

kor  artec  math
a   1.0    7.0   4.0
be  2.0    8.0   5.0
c   3.0    9.0   6.0
d   4.0    4.0   1.0
el  5.0    5.0   2.0
f   6.0    6.0   3.0

In [129]:
d3['sum'] = d3.sum(axis=1)

In [134]:
d3.drop('avg', axis=1)

kor  artec  math    sum
a     1.0    7.0   4.0   12.0
be    2.0    8.0   5.0   15.0
c     3.0    9.0   6.0   18.0
d     4.0    4.0   1.0    9.0
el    5.0    5.0   2.0   12.0
f     6.0    6.0   3.0   15.0
sum  42.0   78.0  42.0  162.0

In [137]:
d3.iloc[3] = [4,3,1,8,4] # 행 번호로 수정하기

In [138]:
d3

kor  artec  math    sum   avg
a     1.0    7.0   4.0   12.0   6.0
be    2.0    8.0   5.0   15.0   7.5
c     3.0    9.0   6.0   18.0   9.0
d     4.0    3.0   1.0    8.0   4.0
el    5.0    5.0   2.0   12.0   6.0
f     6.0    6.0   3.0   15.0   7.5
sum  42.0   78.0  42.0  162.0  81.0

In [142]:
d3.rank()

kor  artec  math  sum  avg
a    1.0    4.0   4.0  2.5  2.5
be   2.0    5.0   5.0  4.5  4.5
c    3.0    6.0   6.0  6.0  6.0
d    4.0    1.0   1.0  1.0  1.0
el   5.0    2.0   2.0  2.5  2.5
f    6.0    3.0   3.0  4.5  4.5
sum  7.0    7.0   7.0  7.0  7.0

In [143]:
d3

kor  artec  math    sum   avg
a     1.0    7.0   4.0   12.0   6.0
be    2.0    8.0   5.0   15.0   7.5
c     3.0    9.0   6.0   18.0   9.0
d     4.0    3.0   1.0    8.0   4.0
el    5.0    5.0   2.0   12.0   6.0
f     6.0    6.0   3.0   15.0   7.5
sum  42.0   78.0  42.0  162.0  81.0

In [8]:
names = input('enter student name: ').split(',')
kor = input('enter kor score: ').split(',')
eng = input('enter eng score: ').split(',')
mat = input('enter mat score: ').split(',')
lecture = ['kor', 'eng', 'mat']

kor = [int (i) for i in kor]
eng = [int (i) for i in eng]
mat = [int (i) for i in mat]

score = pd.DataFrame(index=names, columns=lecture)
score['kor'] = kor
score['eng'] = eng
score['mat'] = mat
score['sum'] = score.sum(axis = 1)
score

enter student name: a,b,c
enter kor score: 1,2,3
enter eng score: 4,5,6
enter mat score: 7,8,9


kor  eng  mat  sum
a    1    4    7   12
b    2    5    8   15
c    3    6    9   18

In [10]:
score.index

Index(['a', 'b', 'c'], dtype='object')

In [11]:
score.columns

Index(['kor', 'eng', 'mat', 'sum'], dtype='object')

In [12]:
score.values

array([[ 1,  4,  7, 12],
       [ 2,  5,  8, 15],
       [ 3,  6,  9, 18]], dtype=int64)

In [13]:
score.var

<bound method DataFrame.var of    kor  eng  mat  sum
a    1    4    7   12
b    2    5    8   15
c    3    6    9   18>

In [14]:
score['kor']

a    1
b    2
c    3
Name: kor, dtype: int64

In [15]:
score.mat

a    7
b    8
c    9
Name: mat, dtype: int64

In [16]:
score[1:3]

kor  eng  mat  sum
b    2    5    8   15
c    3    6    9   18

In [19]:
score

kor  eng  mat  sum
a    1    4    7   12
b    2    5    8   15
c    3    6    9   18

In [20]:
score.eng[1:3]

b    5
c    6
Name: eng, dtype: int64

In [22]:
score.loc['b', 'eng']

5

In [23]:
score.loc['b':'c', 'eng':'mat']

eng  mat
b    5    8
c    6    9

In [24]:
score.iloc[1:3,1:3]

eng  mat
b    5    8
c    6    9

In [26]:
score.iloc[[1,2]]

kor  eng  mat  sum
b    2    5    8   15
c    3    6    9   18

In [31]:
nation = ['afghanistan', 'afghanistan','albania','algeria','angola','argentina', 'australia','australia', 'austria','bahrain']
continent = ['asia','asia','europe','africa','africa','americas','oceania','oceania','europe','asia']
year = [1952,2002,1992,1982,1972,1962,1952,2002,1992,1982]
life = [28.801,42.129,71.581,61.368,37.928,65.142,69.120,80.370,76.010,69.052]
pop = [8425333,25268405,3326498,20033753,5894858,21283783,8691212,1954692,7914969,377967]
gdp = [779.445314,726.734055,249.437901,5745.160213,5473.288005,7133.166023,10039.595640,3068.754730,27042.08680,19211.147310]

data = pd.DataFrame()
data['country'] = nation
data['continet'] = continent
data['year'] = year
data['life'] = life
data['pop'] = pop
data['gdp'] = gdp
data

country  continet  year    life       pop           gdp
0  afghanistan      asia  1952  28.801   8425333    779.445314
1  afghanistan      asia  2002  42.129  25268405    726.734055
2      albania    europe  1992  71.581   3326498    249.437901
3      algeria    africa  1982  61.368  20033753   5745.160213
4       angola    africa  1972  37.928   5894858   5473.288005
5    argentina  americas  1962  65.142  21283783   7133.166023
6    australia   oceania  1952  69.120   8691212  10039.595640
7    australia   oceania  2002  80.370   1954692   3068.754730
8      austria    europe  1992  76.010   7914969  27042.086800
9      bahrain      asia  1982  69.052    377967  19211.147310

In [32]:
data.country

0    afghanistan
1    afghanistan
2        albania
3        algeria
4         angola
5      argentina
6      australia
7      australia
8        austria
9        bahrain
Name: country, dtype: object

In [34]:
data.iloc[:, 0:3]

country  continet  year
0  afghanistan      asia  1952
1  afghanistan      asia  2002
2      albania    europe  1992
3      algeria    africa  1982
4       angola    africa  1972
5    argentina  americas  1962
6    australia   oceania  1952
7    australia   oceania  2002
8      austria    europe  1992
9      bahrain      asia  1982

In [35]:
data.iloc[0]

country     afghanistan
continet           asia
year               1952
life             28.801
pop             8425333
gdp             779.445
Name: 0, dtype: object

In [37]:
data.iloc[[1,3,5]]

country  continet  year    life       pop          gdp
1  afghanistan      asia  2002  42.129  25268405   726.734055
3      algeria    africa  1982  61.368  20033753  5745.160213
5    argentina  americas  1962  65.142  21283783  7133.166023

In [39]:
data.iloc[2:5]

country continet  year    life       pop          gdp
2  albania   europe  1992  71.581   3326498   249.437901
3  algeria   africa  1982  61.368  20033753  5745.160213
4   angola   africa  1972  37.928   5894858  5473.288005

In [41]:
data.iloc[6:10, [0,3,5]]

country    life          gdp
6  australia  69.120  10039.59564
7  australia  80.370   3068.75473
8    austria  76.010  27042.08680
9    bahrain  69.052  19211.14731

In [43]:
data.iloc[[0,2,4],[0,1,4]]

country continet      pop
0  afghanistan     asia  8425333
2      albania   europe  3326498
4       angola   africa  5894858

In [50]:
score

kor  eng  mat  sum
a    1    4    7   12
b    2    5    8   15
c    3    6    9   18

In [51]:
score.kor + score.mat

a     8
b    10
c    12
dtype: int64

In [52]:
x  = score.mat > 7

In [53]:
x

a    False
b     True
c     True
Name: mat, dtype: bool

In [54]:
score[x]

kor  eng  mat  sum
b    2    5    8   15
c    3    6    9   18

In [8]:
score.mat >15

a      False
b       True
c       True
d       True
avg     True
Name: mat, dtype: bool

In [56]:
score.sort_index()

kor  eng  mat  sum
a    1    4    7   12
b    2    5    8   15
c    3    6    9   18

In [58]:
score.sort_values(by='mat', ascending=False)

kor  eng  mat  sum
c    3    6    9   18
b    2    5    8   15
a    1    4    7   12

In [3]:
student = input('enter student names: ').split(',')
kor = input('enter kor score: ').split(',')
eng = input('enter eng score: ').split(',')
mat = input('enter mat score: ').split(',')

kor = [int(i) for i in kor]
eng = [int(i) for i in eng]
mat = [int(i) for i in mat]

score = pd.DataFrame(index=student)
score['kor'] = kor
score['eng'] = eng
score['mat'] = mat
score['total'] = score.sum(axis =1)
score.loc['avg'] = score.sum()//len(student)
print('\n')
print(score)
print('\n')

sort1 = input('sorting data 1:kor 2:eng 3:mat 4:total : ')
sort2 = input('sorting order 1:ascending, 2:descending  : ')
print('\n')

if sort1=='1' and sort2 == '1':
    print(score.sort_values(by = 'kor', ascending = True))
elif sort1 == '1'and sort2 == '2':
    print(score.sort_values(by = 'kor', ascending = False))
elif sort1 == '2'and sort2 == '1':
    print(score.sort_values(by = 'eng', ascending = True))
elif sort1 == '2'and sort2 == '2':
    print(score.sort_values(by = 'eng', ascending = False))
elif sort1 == '3'and sort2 == '1':
    print(score.sort_values(by = 'mat', ascending = True))
elif sort1 == '3'and sort2 == '2':
    print(score.sort_values(by = 'mat', ascending = False))
elif sort1 == '4'and sort2 == '1':
    print(score.sort_values(by = 'total', ascending = True))
elif sort1 == '4'and sort2 == '2':
    print(score.sort_values(by = 'total', ascending = False))
else:
    print('you got a wrong number try again')

print('\n')
name = input('enter name you want: ')
print('\n')
print(score.loc[name])

enter student names: a,b,c,d
enter kor score: 15,56,89,45
enter eng score: 56,89,51,12
enter mat score: 15,56,89,54


     kor  eng  mat  total
a     15   56   15     86
b     56   89   56    201
c     89   51   89    229
d     45   12   54    111
avg   51   52   53    156


sorting data 1:kor 2:eng 3:mat 4:total : 4
sorting order 1:ascending, 2:descending  : 2


     kor  eng  mat  total
c     89   51   89    229
b     56   89   56    201
avg   51   52   53    156
d     45   12   54    111
a     15   56   15     86


enter name you want: b


kor       56
eng       89
mat       56
total    201
Name: b, dtype: int64


In [6]:
customer = pd.DataFrame(columns = col)

while True:
    name = input('name: ')
    if name == '':
        break
    sex = input('sex(m/f): ')
    age = int(input('age: '))
    job = input('job(student,sales,self,pro,etc): ')
    
    col = ['sex', 'age', 'job']
    customer.loc[name] = [sex, age, job]


print('female customer older than 60: ')
print(customer.age>=60)
print('student customer: ')
print(customer.loc['student'])
print('3040 customer: ')
print(50>custmer.age>=30)

name: a
sex(m/f): m
age: 45
job(student,sales,self,pro,etc): etc
name: k
sex(m/f): f
age: 78
job(student,sales,self,pro,etc): pro
name: 
  sex age  job
a   m  45  etc
k   f  78  pro
female customer older than 60: 
a    False
k     True
Name: age, dtype: bool
student customer: 


KeyError: 'student'